CREATE TABLE contestphyte_users (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    first_name TEXT NOT NULL,
    last_name TEXT NOT NULL,
    email_address TEXT NOT NULL UNIQUE,
    password TEXT NOT NULL,
    confirmed_account BOOLEAN DEFAULT FALSE,
    date_created TIMESTAMP NOT NULL default now()
);