CREATE TABLE contestphyte_participants (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    contest_id INTEGER NOT NULL REFERENCES contestphyte_contests(id) ON DELETE CASCADE,
    referrer_id INTEGER,
    is_confirmed BOOLEAN DEFAULT FALSE,
    first_name TEXT NOT NULL,
    last_name TEXT NOT NULL,
    email_address TEXT NOT NULL,
    number_of_referrals INTEGER,
    number_of_entries INTEGER
);